// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Category struct {
	CategoryID  string  `json:"category_id"`
	Name        *string `json:"name"`
	Description *string `json:"description"`
}

type Product struct {
	ProductID   string      `json:"product_id"`
	Name        string      `json:"name"`
	Description *string     `json:"description"`
	Category    []*Category `json:"Category"`
}
